<div style="margin-top: 15px; border-top: 1px solid #e0e0e0; color: #999;\
            padding-top: 6px;">
  Generated by the OSEHRA Technical Journal @ <a target="_blank" href="${host}">${host}</a>.
</div>
